### ISSUE TITLE
Using amp; instead of & in HTML

### ISSUE THREAD

**Issue by griffinlacek** [gonzalo-github/prj-rev-bwfs-dasmoto#1]
Tiny thing! In HTML when using & it's best to use the HTML code & since the browser doesn't always know what & is inside of HTML. Check this out for more codes: http://www.html.am/html-codes/

https://github.com/gonzalo-github/prj-rev-bwfs-dasmoto/blob/master/DasmotoArtsandCrafts/index.html#L9

**Comment by gonzalo-github** [comment]
Dear Griffinlacek,
     I appreciate if you confirm to me that what I should put in the code is "& amp"; instead of only " & "

regards
