### ISSUE TITLE
Use headings instead of <p> tags

### ISSUE THREAD

**Issue by griffinlacek** [gonzalo-github/prj-rev-bwfs-dasmoto#3]
Just a suggestion, but you have all of your section title (brushes, paint, etc) as paragraph elements. Better is to use headings, anywhere from h1-h6. Since you already used h1 as your page title, it'd make sense to make all these h2 elements since they're equal in importance. Just for your consideration!

https://github.com/gonzalo-github/prj-rev-bwfs-dasmoto/blob/master/DasmotoArtsandCrafts/index.html#L12
https://github.com/gonzalo-github/prj-rev-bwfs-dasmoto/blob/master/DasmotoArtsandCrafts/index.html#L20
https://github.com/gonzalo-github/prj-rev-bwfs-dasmoto/blob/master/DasmotoArtsandCrafts/index.html#L28

**Comment by gonzalo-github** [comment]
I get it. It was one of my doubts whether to use "h" or "p", and I did not find any idea what criteria to use to decide on it.
Thanks and regards
