### ISSUE TITLE
Avoid Absolute Links

### ISSUE THREAD

**Issue by griffinlacek** [gonzalo-github/prj-rev-bwfs-dasmoto#4]
This link is broken on any machine other than yours. That's because it's an absolute link (full link path that relates to your specific file structure) We want to use relative links which doesn't specify the whole path so that the file will be accessible on any machine.

Like this:

`./resources/pattern.jpg `

https://github.com/gonzalo-github/prj-rev-bwfs-dasmoto/blob/master/DasmotoArtsandCrafts/css/style.css#L3

**Comment by gonzalo-github** [comment]
Okay. I am grateful for the suggestion that I will take into account in the future.

Thanks and regards
