### ISSUE TITLE
CSS code spacing/bracketing

### ISSUE THREAD

**Issue by griffinlacek** [gonzalo-github/prj-rev-bwfs-dasmoto#5]
Your styles are good and work well, but just a few spots could use some extra spacing and bracket placement. Generally we want this form for a CSS style

```
target {
  styles
}
```

So, we keep a space between the target and { and then start our styles on a new line indented. Mostly you follow this, but just a few spots you could make some minor fixes. Ultimately, this is nitpicking, but writing more readable code is always important for further development and working in teams.

Here's just a few spots to try and change to the preferred format:

https://github.com/gonzalo-github/prj-rev-bwfs-dasmoto/blob/master/DasmotoArtsandCrafts/css/style.css#L1-L3
https://github.com/gonzalo-github/prj-rev-bwfs-dasmoto/blob/master/DasmotoArtsandCrafts/css/style.css#L5-L7
https://github.com/gonzalo-github/prj-rev-bwfs-dasmoto/blob/master/DasmotoArtsandCrafts/css/style.css#L9
https://github.com/gonzalo-github/prj-rev-bwfs-dasmoto/blob/master/DasmotoArtsandCrafts/css/style.css#L11
https://github.com/gonzalo-github/prj-rev-bwfs-dasmoto/blob/master/DasmotoArtsandCrafts/css/style.css#L13

**Comment by gonzalo-github** [comment]
Ok.   I appreciate the suggestion and share the idea that it is important that the code be readable.

Thanks and regard
